[package]
authors = ["nathanfaucett@gmail.com"]
default-run = "toda"
description = "toda"
edition = "2021"
license = ""
name = "toda"
repository = ""
rust-version = "1.84"
version = "0.1.0"

[lib]
crate-type = ["lib", "cdylib", "staticlib"]
name = "toda"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
lazy_static = "1.5"
serde_json = "1"

tauri = { version = "2", features = ["protocol-asset", "devtools", "unstable"] }
tauri-plugin-fs = "2"

sqlx = { version = "0.8", default-features = false, features = [
  "sqlite",
  "runtime-tokio",
] }
tauri-plugin-hypergraphsql = { git = "https://github.com/aicacia/tauri-plugin-hypergraphsql", rev = "4126607" }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
strip = true
